### ISSUE TITLE
Recursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by Guang1234567** [HowardChenhaoyang/RxActivity#1]
https://github.com/HowardChenhaoyang/RxActivity/blob/8468982bbb0e44cded691cc2c3b0db3e381b5c93/library/src/main/java/com/example/library/RxActivity.kt#L14

like Glide bug https://github.com/bumptech/glide/issues/136

I see that the libraries are using viewless Fragments to do work. This creates a problem where under some circumstance, would conflict with other fragment transactions that fragment manager is doing
The full stacktrace:

 java.lang.IllegalStateException: Recursive entry to executePendingTransactions
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1457)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:482)
        at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:148)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:66)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:29)
        at com.bumptech.glide.Glide.with(Glide.java:537)

**Comment by HowardChenhaoyang** [comment]
已解决
